### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by cranberyxl** [king-jam/tracker2jira#7]
I am interested in this very topic. Can you share details in how to configure it?

**Comment by king-jam** [comment]
Apologies for the delay. Github is terrible at notifications.

It's currently under development and not everything works. I'm still in a POC stage on my own JIRA instance internally. 

I'm working on removing some hardcoded fields and need to work on making the API more dynamic in nature.

Probably a week or 2 of work. What's your expectation for capabilities? Can you share an example issue from your internal JIRA instance via the REST API so I can see what fields I need to make dynamic?

**Comment by cranberyxl** [comment]
We're looking to push all the features, chores, and bugs from pivotal to jira. My thought was to use webhooks to listen for changes. What do you need to see on our api?

**Comment by king-jam** [comment]
This is a pull model since most firewalls won't allow incoming webhooks. I designed it to use the Pivotal Activity API to do deltas between the Pivotal tracker instance and the internal JIRA server. (Enterprise problem).

An FYI, if you are using Pivotal Tracker and JIRA Cloud, Pivotal has existing integrations to work with that via webhooks.

If you are still reading and interested:
I need a view of ```GET /rest/api/2/issue/<issue key>```

You can scrub it of anything proprietary, I need to compare the customfields between your instance and mine and start using the variations to adjust the API design.

**Comment by king-jam** [comment]
Assuming the alternative solved your problem. Closing.
